### ISSUE TITLE
That last step...

### ISSUE THREAD

**Issue by PunkStarStudios** [daxko/PassSharp#10]
I have that last step as being this :
            using (var myStream = new MemoryStream())
            {
                PassWriter.WriteToStream(myPass, myStream,
                  new X509Certificate2("MyFiles/AppleWWDRCA.cer"),
                  new X509Certificate2("MyFiles/Certificates.p12", "mypassword"));

            }
But I am getting two exceptions :

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'ServiceStack.Text.JsConfig' threw an exception.
  Source=ServiceStack.Text
  StackTrace:
   at ServiceStack.Text.JsConfig.CreateScope(String config, JsConfigScope scope)
   at PassSharp.PassWriter.ToJson(Pass pass)
   at PassSharp.PassWriter.WriteToStream(Pass pass, Stream stream, X509Certificate2 appleCert, X509Certificate2 passCert)
   at PasskitServer.Controllers.PassesController.Get(String PassTypeId, String LoyGUID) in C:\Users\punky\Documents\Visual Studio 2017\Projects\PasskitServer\PasskitServer\Controllers\PassesController1.cs:line 74
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

Inner Exception 1:
TypeInitializationException: The type initializer for 'ServiceStack.LicenseUtils' threw an exception.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Can someone point out what I am doing wrong?

**Comment by PunkStarStudios** [comment]
Actually - I got past that... found with Net Core 2.0 I had to install the nugget package "System.Configuration.ConfigurationManager"

But now I am getting this error :
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException
  HResult=0x80090029
  Message=The requested operation is not supported
  Source=System.Security.Cryptography.Cng
  StackTrace:
   at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
   at System.Security.Cryptography.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
   at Org.BouncyCastle.Security.DotNetUtilities.GetKeyPair(AsymmetricAlgorithm privateKey)
   at PassSharp.PassWriter.GenerateSignature(Byte[] manifest, X509Certificate2 appleCert, X509Certificate2 passCert)
   at PassSharp.PassWriter.WriteToStream(Pass pass, Stream stream, X509Certificate2 appleCert, X509Certificate2 passCert)
   at PasskitServer.Controllers.PassesController.Get(String PassTypeId, String LoyGUID) in C:\Users\punky\Documents\Visual Studio 2017\Projects\PasskitServer\PasskitServer\Controllers\PassesController.cs:line 74
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
